### ISSUE TITLE
建议加个循环判断，昨天出bug了，一直投币导致账号异常

### ISSUE THREAD

**Issue by catbreast** [r3inbowari/bilicoin#22]
23点失败了一次，就一直投到第二天早上9点多。
[W] 2022-01-14 23:50:30 [bili.go:518] [CRON] task failed {"TaskID":"3a43d042-a6ec-47ef-b99f-ca65b0c41350","UID":"xxxxxx"}
ited {"AVID":"935524117","BVID":"BV1pT4y1m7z4","UID":"x","dropCount":3}
[I] 2022-01-15 09:35:56 [bili.go:405] [TASK] Drop limited {"AVID":"935524117","BVID":"BV1pT4y1m7z4","UID":x","dropCount":3}
[I] 2022-01-15 09:36:39 [bili.go:405] [TASK] Drop limited {"AVID":"765515481","BVID":"BV1Mr4y1v7Cm","UID":"x","dropCount":3}
[I] 2022-01-15 09:36:56 [bili.go:405] [TASK] Drop limited {"AVID":"978059269","BVID":"BV1p44y1578P","UID":"x","dropCount":3}
[I] 2022-01-15 09:37:04 [bili.go:405] [TASK] Drop limited {"AVID":"978059269","BVID":"BV1p44y1578P","UID":"x","dropCount":3}
[I] 2022-01-15 09:39:07 [config.go:56] [FILE] update user configuration {"size":1690}
[I] 2022-01-15 09:39:07 [bili.go:521] [CRON] task completed {"UID":"327923607"}
[I] 2022-01-15 23:50:30 [config.go:56] [FILE] update user configuration {"size":973}
[I] 2022-01-15 23:50:30 [bili.go:371] [USER] Drop history {"UID":"327923607","dropCount":0}
[I] 2022-01-15 23:50:35 [config.go:56] [FILE] update user configuration {"size":879}
[W] 2022-01-15 23:50:35 [bili.go:518] [CRON] task failed {"TaskID":"3a43d042-a6ec-47ef-b99f-ca65b0c41350","UID":"xxxxx"}
[I] 2022-01-15 23:54:28 [config.go:56] [FILE] update user configuration {"size":879}
[I] 2022-01-15 23:54:28 [bili.go:521] [CRON] task completed {"UID":"327923607"}

**Comment by r3inbowari** [comment]
v1.1.0及以下的版本确实有这个问题，“投着投着突然就结束了”。v1.1.1修复了这个问题

**Comment by r3inbowari** [comment]
还有就是投币限制的问题，鬼畜区那个api有问题，现在改成了热门区，基本上不会出现drop limit
