### ISSUE TITLE
你好，我想请问一下关于二维码的问题

### ISSUE THREAD

**Issue by MeowxYee** [r3inbowari/bilicoin#25]
我在B站抓请求的时候，抓到 passport.bilibili.com/qrcode/getLoginUrl ，可以返回 一串json，里面包含 url 和 oauthKey

其中url是一个重定向，我也不知道有啥用？

然后，B站的二维码，我查了网页的结构，直接是base64的格式，我特别想获取二维码~~~看到了作者演示那里竟然有二维码，太牛了

请问一下作者，您是怎么获取二维码的？

**Comment by r3inbowari** [comment]
没错，url就是一个重定向，只不过在手机客户端扫码时会在请求头注入一些手机客户端的参数而已。

其实 readme 上面已经写的很清楚了。
`注意：二维码的数据格式是 https://passport.bilibili.com/qrcode/h5/login?oauthKey=<oauth key>`

这个字符串就是二维码的实际数据，至于用不用base64，那取决于你。

**Comment by MeowxYee** [comment]
“这个字符串就是二维码的实际数据”————谢谢哥哥，听到这句话我瞬间顿悟。因为之前写过知乎的二维码登录，知乎是 请求之后返回一个token，然后根据token拼接字符串，就是二维码的URL，我还是第一次遇见B站这种方式生成二维码的，真有意思。谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "r3inbowari/bilicoin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 凌晨1:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [r3inbowari/bilicoin] 你好，我想请问一下关于二维码的问题 (Issue #25)





 
没错，url就是一个重定向，只不过在手机客户端扫码时会在请求头注入一些手机客户端的参数而已。
 
其实 readme 上面已经写的很清楚了。
 注意：二维码的数据格式是 https://passport.bilibili.com/qrcode/h5/login?oauthKey=<oauth key&gt;
 
这个字符串就是二维码的实际数据，至于用不用base64，那取决于你。

**Comment by r3inbowari** [comment]
> “这个字符串就是二维码的实际数据”————谢谢哥哥，听到这句话我瞬间顿悟。因为之前写过知乎的二维码登录，知乎是 请求之后返回一个token，然后根据token拼接字符串，就是二维码的URL，我还是第一次遇见B站这种方式生成二维码的，真有意思。谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "r3inbowari/bilicoin" ***@***.***&gt;; 发送时间:&nbsp;2022年4月26日(星期二) 凌晨1:06 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [r3inbowari/bilicoin] 你好，我想请问一下关于二维码的问题 (Issue #25) 没错，url就是一个重定向，只不过在手机客户端扫码时会在请求头注入一些手机客户端的参数而已。 其实 readme 上面已经写的很清楚了。 注意：二维码的数据格式是 https://passport.bilibili.com/qrcode/h5/login?oauthKey=<oauth key&gt; 这个字符串就是二维码的实际数据，至于用不用base64，那取决于你。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

B站和b乎都是oauth那套，整个登录过程大同小异。
