### ISSUE TITLE
您好，关于 [未知设备] 的情况怎么处理

### ISSUE THREAD

**Issue by MeowxYee** [r3inbowari/bilicoin#26]
在网页上对B站的网站进行扫描的时候，是可以正常显示设备的，设备名字为Chrome

![image](https://user-images.githubusercontent.com/18101168/181812199-1fb82804-f9a2-4c0a-92b2-cae80caba356.png)

但是如果我在自己写的爬虫上面进行登录的话，会显示 [未知设备]

![image](https://user-images.githubusercontent.com/18101168/181813934-6663102c-c1f7-44b4-88fe-73515de3c79c.png)

您好，怎么让设备也变成是Chrome，我不知道哪一步出现了问题，我的UA标识也是加进去的(就是Chrome的标识)，但是依旧是 [未知设备]，您知道如何解决吗

**Comment by r3inbowari** [comment]
可以提供一下你的代码吗

**Comment by r3inbowari** [comment]
这个问题可能是 `canvas_finger` 这个参数造成的。
不一定说加了 ua 标识就是你设置的标识的，服务商会考虑提高终端设备的识别精确度，通常会结合这个参数。
具体你可以了解一下 `canvas fingerprinting`。

https://www.mozilla.org/en-US/firefox/features/block-fingerprinting/
https://browserleaks.com/canvas

**Comment by MeowxYee** [comment]
实在是太感谢你的热心解答了，我还是第一次知道有这个东西的存在。我正在改变我的登录模式，不再采用原先的抓请求，编写请求过程的方式，现在我用事实去加载登录页面，然后去获取div中的svg的二维码图片。这样应该就不会被显示“设备未知/异常”了。最后！感谢！

**Comment by MeowxYee** [comment]
我今天算是彻底解决了这个问题，因为我看到了一份登录逼站的代码。逼站扫码登录把参数写到url上面，竟然就可以不会显示未知设备。这也挺奇怪的。不过，总的来说最终还是解决了，谢谢你的回复捏~
